name: Spacegame Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.9.x, 14.x]
        dotnet-version: [ '3.1.x', '6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Node.js modules as defined in package.json.
      run: npm install --quite
    
    - name: Compile Sass (.scss) files to standard CSS (.css)
      run: node-sass Tailspin.SpaceGame.Web/wwwroot
      
    - name: Minify JavaScript and CSS files
      run: echo `date` > Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt
      
    - name: Minify JavaScript and CSS files.
      run: gulp
